#!/bin/bash
cat ../cheat.log | grep "result" | tail -n 1 | python -mjson.tool > inv.json
echo $(cat inv.json | grep portalTitle | wc -l)" KEYS:"
cat inv.json | grep portalTitle | cut -d'"' -f 4
echo $(cat inv.json | grep -B 1 EMITTER_A | grep '"level": 1' | wc -l) "x L1 RESO"
echo $(cat inv.json | grep -B 1 EMITTER_A | grep '"level": 2' | wc -l) "x L2 RESO"
echo $(cat inv.json | grep -B 1 EMITTER_A | grep '"level": 3' | wc -l) "x L3 RESO"
echo $(cat inv.json | grep -B 1 EMITTER_A | grep '"level": 4' | wc -l) "x L4 RESO"
echo $(cat inv.json | grep -B 1 EMITTER_A | grep '"level": 5' | wc -l) "x L5 RESO"
echo $(cat inv.json | grep -B 1 EMITTER_A | grep '"level": 6' | wc -l) "x L6 RESO"
echo $(cat inv.json | grep -B 1 EMITTER_A | grep '"level": 7' | wc -l) "x L7 RESO"
echo $(cat inv.json | grep -B 1 EMITTER_A | grep '"level": 8' | wc -l) "x L8 RESO"
echo $(cat inv.json | grep -B 1 EMP_BURSTER | grep '"level": 1' | wc -l) "x L1 XMP"
echo $(cat inv.json | grep -B 1 EMP_BURSTER | grep '"level": 2' | wc -l) "x L2 XMP"
echo $(cat inv.json | grep -B 1 EMP_BURSTER | grep '"level": 3' | wc -l) "x L3 XMP"
echo $(cat inv.json | grep -B 1 EMP_BURSTER | grep '"level": 4' | wc -l) "x L4 XMP"
echo $(cat inv.json | grep -B 1 EMP_BURSTER | grep '"level": 5' | wc -l) "x L5 XMP"
echo $(cat inv.json | grep -B 1 EMP_BURSTER | grep '"level": 6' | wc -l) "x L6 XMP"
echo $(cat inv.json | grep -B 1 EMP_BURSTER | grep '"level": 7' | wc -l) "x L7 XMP"
echo $(cat inv.json | grep -B 1 EMP_BURSTER | grep '"level": 8' | wc -l) "x L8 XMP"
echo $(cat inv.json | grep -B 1 POWER_CUBE | grep '"level": 1' | wc -l) "x L1 CUBE"
echo $(cat inv.json | grep -B 1 POWER_CUBE | grep '"level": 2' | wc -l) "x L2 CUBE"
echo $(cat inv.json | grep -B 1 POWER_CUBE | grep '"level": 3' | wc -l) "x L3 CUBE"
echo $(cat inv.json | grep -B 1 POWER_CUBE | grep '"level": 4' | wc -l) "x L4 CUBE"
echo $(cat inv.json | grep -B 1 POWER_CUBE | grep '"level": 5' | wc -l) "x L5 CUBE"
echo $(cat inv.json | grep -B 1 POWER_CUBE | grep '"level": 6' | wc -l) "x L6 CUBE"
echo $(cat inv.json | grep -B 1 POWER_CUBE | grep '"level": 7' | wc -l) "x L7 CUBE"
echo $(cat inv.json | grep -B 1 POWER_CUBE | grep '"level": 8' | wc -l) "x L8 CUBE"
echo $(cat inv.json | grep MEDIA | wc -l) "x MEDIA"
echo $(cat inv.json | grep -B 1 SHIELD | grep COMMON | wc -l) " x COMMON SHIELD"
echo $(cat inv.json | grep -B 1 SHIELD | grep RARE | wc -l) " x RARE SHIELD"
echo $(cat inv.json | grep -B 1 SHIELD | grep VERY_RARE | wc -l) " x VERY RARE SHIELD"
echo $(cat inv.json | grep -B 1 HEATSINK | grep COMMON | wc -l) " x COMMON HEAT SINK"
echo $(cat inv.json | grep -B 1 HEATSINK | grep RARE | wc -l) " x RARE HEAT SINK"
echo $(cat inv.json | grep -B 1 HEATSINK | grep VERY_RARE | wc -l) " x VERY RARE HEAT SINK"
echo $(cat inv.json | grep -B 1 MULTIHACK | grep COMMON | wc -l) " x COMMON MULTIHACK"
echo $(cat inv.json | grep -B 1 MULTIHACK | grep RARE | wc -l) " x RARE MULTIHACK"
echo $(cat inv.json | grep -B 1 MULTIHACK | grep VERY_RARE | wc -l) " x VERY RARE MULTIHACK"
echo $(cat inv.json | grep FORCE_AMP | wc -l) "x FORCE AMP"
echo $(cat inv.json | grep LINK_AMP | wc -l) "x LINK AMP"
echo $(cat inv.json | grep TURRET | wc -l) "x TURRET"
echo $(cat ../cheat.log | grep \"ap\" | tail -n 1 | python -mjson.tool | grep '"ap"' | cut -d'"' -f4) "AP"
